# Generated by Django 5.0.3 on 2025-04-22 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='poststatistic',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='scheduledpost',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': True},
        ),
    ]
