# Generated by Django 5.0.3 on 2025-05-15 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_alter_notification_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={
                'db_table': 'dashboard_assistant',
                'ordering': ['-id'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='poststatistic',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scheduledpost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='dashboard.users'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='users',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='AssistantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assistant', models.ForeignKey(db_column='assistant_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.assistant')),
            ],
            options={
                'db_table': 'dashboard_assistant_tags',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True)),
                ('assistants', models.ManyToManyField(related_name='tags', through='dashboard.AssistantTag', to='dashboard.assistant')),
            ],
            options={
                'db_table': 'dashboard_tag',
                'ordering': ['name'],
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='assistanttag',
            name='tag',
            field=models.ForeignKey(db_column='tag_id', on_delete=django.db.models.deletion.CASCADE, to='dashboard.tag'),
        ),
        migrations.CreateModel(
            name='TrackingLinkStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('click_count', models.IntegerField()),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.users')),
            ],
            options={
                'db_table': 'tracking_link_stats',
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='assistanttag',
            index=models.Index(fields=['assistant', 'tag'], name='dashboard_a_assista_7ae228_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trackinglinkstats',
            unique_together={('user', 'date')},
        ),
    ]
